### ISSUE TITLE
Crashing when teleporting to/away a soul cage spawner

### ISSUE THREAD

**Issue by hkmag** [CodexAdrian/Spirit#1] opened 2021-07-23 10:34 UTC
This happens when using the mod "Waystones" to teleport far away from or to a spawner that is currently spawning mobs. For example, I crash when I use the Waystone at my in-game house at coords "50, 50" (which has a soul cage with a tier 4 magma crystal close by) and teleport to another Waystone at coords "800, 800" which is right next to a lit end portal in a stronghold. The same happens when I use the Waystone at the end portal to teleport back to the Waystone at my house. 

This happens with everyone on my server, and it only crashes the client who teleported, not the server. 

I am using Spirit version 1.0.5 (the latest version), and I am on Minecraft 1.17.1

Here is the full crash log:
[crash-2021-07-22_01.39.09-client.txt](https://github.com/CodexAdrian/Spirit/files/6868139/crash-2021-07-22_01.39.09-client.txt)

**Comment by voodoonofx** [comment] 2021-08-05 23:53
I can confirm this happens when the mod is used as part of a Modpack. Have not tried using only this mod by itself. It seems to be related to the blue glow being applied to the mobs. If this can be configurable (disable-able), that might solve the problem for many users.

I'm using Spirit as part of the "Better Minecraft v6 - Fabric" modpack on 1.17.0

**Comment by CodexAdrian** [comment] 2021-08-25 00:09
Fixed in latest commit, update on CF soon

**Closed by CodexAdrian** 2021-08-25 00:09 UTC
